___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list = np.array([5,10,15,20,25])
my_list

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [4]:
np.ones((4,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [5]:
np.ones((4,4)) * 7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### 6. Create same array above with full method

In [6]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [7]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [8]:
np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [9]:
np.linspace(start = [0,1,2,3,4], stop = [20,21,22,23,24],num = 5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [10]:
np.random.rand(5)

array([0.09450135, 0.24008725, 0.41155732, 0.76666946, 0.04713428])

#### 11. Create random normal distributed 5x5 array

In [11]:
np.random.rand(5,5)

array([[0.3070807 , 0.28711131, 0.02856057, 0.84630865, 0.06308357],
       [0.97094251, 0.90711618, 0.40661123, 0.22157053, 0.74429233],
       [0.80919756, 0.66182573, 0.13993417, 0.87867588, 0.79751938],
       [0.86464873, 0.70319411, 0.59058153, 0.9890888 , 0.91581316],
       [0.44967236, 0.83248977, 0.84280412, 0.48476886, 0.84600652]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [12]:
np.random.randint(20,50, size= (3,4), dtype = int)

array([[24, 30, 45, 44],
       [33, 41, 27, 24],
       [43, 29, 33, 38]])

#### 13. Reshape the array below with shape 6x8

In [13]:
ranarr = np.random.randint(0, 60, 48)
ranarr

array([ 3, 43, 37, 17, 19, 12, 39, 10, 48, 49, 34, 38, 51, 24,  2, 20, 54,
       52, 49, 32, 17, 52,  6, 40, 30, 46, 22, 55, 42, 25,  6, 50,  6,  8,
        6, 16,  4, 22,  3, 53, 17, 42, 47, 29, 20, 55, 14,  6])

In [14]:
ranarr.reshape(6,8)

array([[ 3, 43, 37, 17, 19, 12, 39, 10],
       [48, 49, 34, 38, 51, 24,  2, 20],
       [54, 52, 49, 32, 17, 52,  6, 40],
       [30, 46, 22, 55, 42, 25,  6, 50],
       [ 6,  8,  6, 16,  4, 22,  3, 53],
       [17, 42, 47, 29, 20, 55, 14,  6]])

In [15]:
ranarr.reshape(6,-1)

array([[ 3, 43, 37, 17, 19, 12, 39, 10],
       [48, 49, 34, 38, 51, 24,  2, 20],
       [54, 52, 49, 32, 17, 52,  6, 40],
       [30, 46, 22, 55, 42, 25,  6, 50],
       [ 6,  8,  6, 16,  4, 22,  3, 53],
       [17, 42, 47, 29, 20, 55, 14,  6]])

## Numpy Indexing and Selection


In [16]:
my_array = np.arange(1,17).reshape(4,4)
my_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [17]:
my_array[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [18]:
my_array[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [19]:
my_array[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [20]:
my_array[:,2] = 77
my_array

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [21]:
one_num = my_array[1,0]
two_num = my_array[3,2]

np.array([one_num,two_num])                # Hocam bu soru başka türlü yapılıyorsa bana geri dönüş sağlarsanız sevinirim.:)

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [22]:
my_array[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [23]:
my_array[my_array < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [24]:
my_array[my_array > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [25]:
my_array[my_array < 10] + my_array[my_array > 12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [26]:
std_deviation = my_array[my_array < 10] + my_array[my_array > 12]

std_deviation.std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [27]:
my_array

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [28]:
my_array[:,1].sum()

32

#### 23. Get the median,mean and std of 3rd column from array above

In [29]:
# mistake in the question. I get the first array's third raw below.

test = np.arange(1,17).reshape(4,4)

np.median(test[2,:])


10.5

In [30]:
np.mean(test[2,:])

10.5

In [31]:
np.std(test[2,:])

1.118033988749895

# Pandas Section

In [32]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [33]:
df = pd.read_csv(r"C:\Users\Hansa\Desktop\Salaries.csv")

salaries = pd.DataFrame(df)

pd.DataFrame(df, index= [0,1,2,3,4])

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [34]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [35]:
salaries.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [36]:
salaries["Year"].value_counts() 


2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [37]:
salaries["TotalPay"].max()

567595.43

In [38]:
salaries["TotalPay"].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [39]:
len(salaries[(salaries["TotalPay"] > salaries["TotalPay"].mean())])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [40]:
salaries[2:3]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [41]:
lowest = salaries['TotalPayBenefits'].idxmin()

salaries.loc[lowest][["EmployeeName",]]

EmployeeName    Joe Lopez
Name: 148653, dtype: object

**What are the unique Jobs in dataset?**

In [42]:
salaries["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [43]:
salaries["JobTitle"].value_counts()[-4:-1]

TRAFFIC SIGNAL OPERATOR                    1
PUBLIC SAFETY COMMUNICATIONS TECHNICIAN    1
STATISTICIAN                               1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [67]:
avg = salaries["TotalPayBenefits"].mean()

year2012 = salaries[salaries.Year == 2012]["TotalPayBenefits"].value_counts()



NameError: name 'sal' is not defined

**How many people have the word Manager in their job title?**

In [69]:
def find_manager(JobTitle):    
    if 'Manager' in JobTitle.lower().split():
        return True
    else:
        return False


sum(salaries['JobTitle'].apply(lambda x: find_manager(x)))




0

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
salaries.groupby("Year").sum()

twelve = salaries[salaries.Year == 2012]["TotalPayBenefits"]

twelve.mean() < twelve 

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

**Print out the names of the employees who earn more than min, but less than avg**